### ISSUE TITLE
Question about deleting expired events

### ISSUE THREAD

**Issue by wardes** [otobus/event_bus_postgres#1]
Hi, 
 Firstly, thanks for making event_bus and event_bus_postgres.  I was hoping to use event_bus_postgres as a permanent store of events that we could process independently for analysis etc, but the combination of a default TTL and the TTL expiry job running all the time means that all the events will be deleted eventually.

Is this the intended use case for event_bus_postgres?

We may end up sending all events to an external system but for now this looks like a good solution.  I'm considering making a fork to enable/disable the TTL job via a config setting, as well as a switchable mechanism for serialisation of the data field - storing the data in json would mean it's easier to decode in other programming languages.

Thanks,
Simon

**Comment by andreapavoni** [comment]
does the following config enable/disable auto-deletion?

```
auto_delete_with_ttl: {:system, "EB_PG_AUTO_DELETE_WITH_TTL", "true"},
```

**Comment by mustafaturan** [comment]
Hi @wardes 

Event deletion is set to true with `ttl` by default. If you need to keep events forever then you can set the config value as `false` like @andreapavoni mentioned in his comment.
```elixir
config :event_bus_postgres,
  ...,
  auto_delete_with_ttl: {:system, "EB_PG_AUTO_DELETE_WITH_TTL", "false"},
  ...
```

Final thoughts, feel free fork and implement your own consumer. Again like @andreapavoni said; binary is used to cover any data type. If you need json/xml/etc, you will also need to implement json/xml/etc encoder/decoder for any kind of event data.  Ofcouse, It is possible to support both, but there is no plan for it.

**Comment by wardes** [comment]
Hi, thanks for your replies.  In the end for my current project I've written a few consumers, one of which forwards the events to Elastic Search for processing later, but in a future project I'll investigate this option again, I like the idea of having a permanent store without using any other external systems.

The use of term_to_binary vs JSON will make a difference to whether I could use an external program connecting directly to the Postgres table, or whether I could do the event analysis in Elixir afterwards, or some way to stream data out etc, as you say it's all pretty flexible.

**Comment by mustafaturan** [comment]
@wardes 
np, feel free share your generic consumers. I will be happy to put a link on [wiki page](https://github.com/otobus/event_bus/wiki/Addons)
