### ISSUE TITLE
Repo url configuration overriden on initialization

### ISSUE THREAD

**Issue by thekvn** [otobus/event_bus_postgres#3]
https://github.com/otobus/event_bus_postgres/blob/master/lib/event_bus_postgres/repo.ex#L7-L9

The repo URL configuration is overridden with value from env var `EB_PG_DATABASE_URL` upon initialization, prevents our configuration from using url: for db configuration

**Comment by mustafaturan** [comment]
Hi @thekvn,

This is not a library issue, please ask to stackoverflow. 

Thanks for your understanding

**Comment by thekvn** [comment]
This hard coding of the url keyword argument override prevents us from using the library properly....

**Comment by mustafaturan** [comment]
It is still not an issue. You could assign the env var (`EB_PG_DATABASE_URL `) to make it work on the `0.3.x` versions. Next time please ask to Stackoverflow. 

But I made a little enhancement on version `~> 0.4.0`. You will need to follow need instructions written on README to set it up.
