### ISSUE TITLE
deal with stored events in  terminated OTP consumers

### ISSUE THREAD

**Issue by floodico** [otobus/event_bus_postgres#83]
Hello! 
For example, i have  GenServer as an EventBus consumer. And without using this dependency, the events are simply lost (in case my GenServer terminates unexpectedly). But when to use it, the events are being processed at this step: https://github.com/otobus/event_bus_postgres/blob/1c09e6e9a57b249d91f4a58073fa5c28df24a524/lib/event_bus_postgres.ex#L11-L13
And event's `occured_at` field is set already. That means that event is processed even without the consumer. I hope i understood it correct?!

**Comment by mustafaturan** [comment]
hey @floodico, this is by design of this example library. I highly recommend building your own solution for your cases. I hope this example library helps you to understand usage of event_bus and gen stage together.
